# Docker Compose will create a service using the name of your root directory
services:
# docker compose create a image using the name web. The image name would be something like ${root-dir-name}-web
  web:
    # we will use httpweb image
    # we will create httpweb image 
    # using docker command, see readme.md file for this
    image: httpweb
    # We will tell docker compose to map port 80, 
    # so that we can access from host machine
    ports:
      - "80:80"
      # I am creating another mapping for better understanding
      - "8080:80"

